def projectDir = '/home/azmathasan92/.jenkins/workspace/test/akka-http'

pipeline{
    agent any

    options {
        skipDefaultCheckout true
    }

    stages{

        stage('code-compile'){
            steps {
                dir(projectDir) {
                    sh "mvn test"
                }
            }
        }




   }



}