def projectDir = '/home/azmathasan92/.jenkins/workspace/monorepo-experiments-master/lagom-service'

pipeline{
    agent {
        node {
            label 'master'
            customWorkspace 'monorepo-experiments-master'
        }
    }

    options {
        skipDefaultCheckout true
    }

    stages{

        stage('code-compile'){
            steps {
                dir(projectDir) {
                    sh "mvn test"
                }
            }
        }




   }



}